### PR TITLE
Added transformation functions for will* conditions

### PR DESCRIPTION
**Pull request by velis74**
I have added a parameter to each of the will\* functions that allows to transform the resolved value.

This allows partial comparisons, e.g. actual.length == 100

The .will() function can accept either the message or the function as its second parameter. The other two accept it as their final parameter (they don't perform any detection on parameter type)

Thanks for this great plugin.

### CODE REVIEW

**Comment by bahmutov** [comment]
good feature, but can you fix the Travis unit tests?

**Comment by velis74** [comment]
I have no idea how. The posted code works on my machine and I don't see what's wrong with Travis. It just says "failed, see previous exceptions". But I see no previous exceptions.

**Comment by bahmutov** [comment]
ok, will debug the failed unit tests right now, thanks for the code!

**Comment by bahmutov** [comment]
Fixed the api and tests and published as 0.2.0 https://github.com/bahmutov/qunit-promises/releases/tag/v0.2.0

**Pull request merged**
